name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run : npm i
      shell: bash
    - run : npm run deploy
      shell: bash

    - uses: OctoMind-dev/automagically-action-execute@v2
      with:
        url: https://sker65.github.io/test-app
        token: ${{ secrets.AUTOMAGICALLY_TOKEN }}
        testTargetId: c40207d8-faf7-4197-b860-478c6d5acd0c
        blocking: false
